name: bmi_calculator
description: The BMI (Body Mass Index) Calculator is a Flutter-based app designed to help users monitor their health and fitness journey. This user-friendly app provides a quick and easy way to calculate BMI and gain valuable insights into overall health.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  photo_view: ^0.14.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
